### PR TITLE
Gensim docker

### PR DESCRIPTION
**Pull request by sverhoeven**
* Improve insert speed by
    * Replacing calls to save in a loop by single [bulk create](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#bulk-create). Uses more memory, but much less database queries
    * Compute overlap scores using single SQL statement instead of fetching all data to Python and updating scores. Only used when uploading gensim result
* Adds [gensim](https://radimrehurek.com/gensim/) for lda calculation
    * run_gensim.py script to run
        * `corpus` sub command to convert masspec file to corpus json
        * `gensim` sub command to perform lda using gensim outputting single json file with corpus and lda results
        * `insert` sub command to insert json file with corpus and lda results into database
        * `gensim --ldaformat gensim` sub command to perform lda using gensim outputting gensim formatted output
        * `insert_gensim` sub command to insert json file with corpus and gensim formatted lda results files into database
    * Upload gensim form to upload gensim results into database
* Docker-compose file for production version ms2lda website
* Use Redis as Celery job queue instead of RabbitMQ, as it is easier to setup
* Improved README
* Database schema has not been changed
* Updated requirements.txt and use pipenv to setup environment

### CODE REVIEW

**Comment by sdrogers** [comment]
All looks ok - just a couple of queries:
- Will we need to change the setup on the server re redis / rabbitmq?
- What changed to allow pipenv?

**Comment by sverhoeven** [comment]
To use redis you will need to run a redis daemon on the server and the settings.py must include the line `CELERY_BROKER_URL= "redis://localhost:6379/0"`. 

Pipenv files are generated from the requirements.txt, so only the requirements.txt file was made more complete.

**Comment by sverhoeven** [comment]
1. Redis and debug moved to own settings file
2. Upload gensim form is only visible to members of extra users table

**Comment by sverhoeven** [comment]
3. Created CHEMSPIDER_APIKEY const in settings files which is used by all chemspider code.

PS [Chembl API](https://www.ebi.ac.uk/chembl/api/data/docs) has a image endpoint, eg. 
https://www.ebi.ac.uk/chembl/api/data/image/KXEBOYWJADRGHW-SFHVURJKSA-N (https://www.ebi.ac.uk/chembl/api/data/image/KXEBOYWJADRGHW-SFHVURJKSA-N)

**Comment by justinjjvanderhooft** [comment]
What does the Chembl API need to draw a structure? :)

**Comment by justinjjvanderhooft** [comment]
Is it just the InchIKEY?

**Comment by sverhoeven** [comment]
Yep, ChEMBL ID or Standard InChI Key

**Comment by sverhoeven** [comment]
@sdrogers PR is ready to be merged.

**Comment by sdrogers** [comment]
Ok, done, thanks!

**Pull request merged**
